name: TranscriptPipeline
channels:
  - conda-forge
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.11
  - montreal-forced-aligner
  - pytorch
  - torchaudio
  - pytorch-cuda=11.8 # Might not need cuda if on a mac
  - ffmpeg
  - pandas
  - pip
  - pip:
    - faster-whisper
    - torchcodec
    - TextGrid
    - lingua-language-detector
    - fastapi
    - uvicorn
    - python-multipart
    - transformers
    - peft
    - soundfile
    - silero-vad
    - vosk
    - torch